export const ROUTES = {
  APP: {
    HOME: "/",
    FEED: "/feed",
    PROFILE: "/profile",
    MESSENGER: "/messenger",
    SEARCH: "/search",
    STATISTICS: "/statistics",
    FAVORITES: "/favorites",
    SETTINGS: "/settings",
    TERMS: "/terms",
    PRIVACY: "/privacy",
    ERROR404: "/error404",
  },
  AUTH: {
    LOGIN: "/login",
    SIGNUP: "/signup",
    FORGOT_PASSWORD: "/forgot-password",
    PASSWORD_RECOVERY: "/password-recovery",
    CREATE_NEW_PASSWORD: "/create-new-password",
    EMAIL_VERIFIED: "/signup-email-verified",
    VERIFICATION_EXPIRED: "/verification-expired",
    GITHUB_OAUTH: "/auth/github",
    GOOGLE_OAUTH: "/auth/callback",
  },
} as const;
